### ISSUE TITLE
Incomplete stack is downloaded

### ISSUE THREAD

**Issue by jdanial** [idr-contrib/community#15]
Hi,

I am trying to download the stack of images (as TIFF) from the following link:

https://idr.openmicroscopy.org/webclient/?show=image-1885617

Only a single image is being downloaded. How can I download the full stack?

Best wishes, John.

**Comment by manics** [comment]
@jdanial Hi John, the IDR currently has limited download options. For most of the datasets web downloads are impractical due to the size or number of files, especially with high content screens, so we recommend an external tool Aspera, and have a preconfigured Docker image: https://github.com/IDR/aspera-client-docker

For example, this would download the original raw data for the above image to `/tmp/data`:
`docker run -ti --rm -v /tmp/data:/data imagedata/download idr0023 20160419-original/EllenbergGroupData_for_IDR/Nucleoporins/Nup107/Nup107-aa33-51_antibody/130424_Nup107_1/AllParticles/all_particles.tif /data`

The sub-path can be found from the `Show file paths on server` button
<img width="767" alt="screen shot 2018-10-10 at 10 07 14" src="https://user-images.githubusercontent.com/1644105/46725676-97cf0680-cc74-11e8-9062-ed9cedfb7d38.png">

Unfortunately for individual images this is excessively complicated. We'll discuss this issue next week.

**Comment by joshmoore** [comment]
Hi @jdanial. Did you have any success with this? If not, or if aspera will not work for you in general, perhaps you can tell us more about what you are trying to achieve? Does the format matter? Does it need to be via the browser?

**Comment by jdanial** [comment]
Hi Josh,

Everything worked fine with a docker - many thanks for your help!

**Comment by joshmoore** [comment]
Great to hear.
