### ISSUE TITLE
Access to original image files

### ISSUE THREAD

**Issue by jkh1** [idr-contrib/community#23]
Is there a way to access original image files? 
For example, I'd like to access the original file for this image: https://idr.openmicroscopy.org/webclient/img_detail/3509499/?dataset=1253
It would seem possible to access it since the web client provides the following info:
Imported from:
uod/idr/filesets/idr0045-reichmann/20180806-renamed/Figure01C/Prometaphase4.lif
Paths on server:
demo_2/2018-08/23/10-18-29.255/Prometaphase4.lif

but I can't find a documented web API for accessing it.

Alternatively, I tried the python API but the call demonstrated in the Jupyter notebook (code below) only retrieves one slice of the data:
```
from idr import connection  
import matplotlib.pyplot as plt
conn = connection()
def saveEntireImage(imageId):
    image = conn.getObject("Image", imageId)
    imagePixels = image.getPrimaryPixels().getTile()
    plt.imsave('im_tissue_' + imageId + '.tiff', imagePixels, format='tif')
saveEntireImage("3509499")
```
If the original file is not accessible, I imagine it should be possible to retrieve all slices one by one or even together but I can't find documentation for the methods associated with the image object. 
Any pointer to documentation or code to download a n-dimensional image would be appreciated.

**Comment by manics** [comment]
The original files aren't currently available through an OMERO API due to their size. It's something we're working on, but for now you can use Aspera to download the raw data. Please see the instructions on https://idr.openmicroscopy.org/about/download.html

For example
`docker run -ti --rm -v /tmp/data:/data imagedata/download idr0045 20180806-renamed/Figure01C/Prometaphase4.lif /data`
will download that image to `/tmp/data`

**Comment by jkh1** [comment]
@manics Thanks. I'll give it a try.

**Comment by jkh1** [comment]
@manics  I managed to download the file with the aspera command line client but not with the docker container. With the latter I get the following error:
Error 51 [Destination: Permission denied] 
which seems related to a bug in some older version of the ascp client on Linux (just can't find the page where I saw this). It may be worth updating the container.

**Comment by manics** [comment]
@jkh1 The docker image runs with a fixed UID inside the container. When you mount a host directory into the image you need to make sure that UID has write access to the directory. On Docker for Mac this is usually done automatically (since Docker is actually run on a virtual machine) but on Linux the directory permissions may be incorrect.

**Comment by jkh1** [comment]
@manics Thanks. This was indeed a directory permission issue.
