### ISSUE TITLE
idr0016: broken plates (corrupted TIFF files)

### ISSUE THREAD

**Issue by sunyi000** [idr-contrib/community#26]
I'm trying to download images using api, and one of the error appears during downloading.

it seems to do with omero gateway.

I'm not sure what is happening and how do debug..so any pointers are much appreciated

other images can be downloaded successfully with the same python code.

Thank you very much

ResourceError: exception ::omero::ResourceError
{
    serverStackTrace = ome.conditions.ResourceError: Error instantiating pixel buffer: /data/OMERO/ManagedRepository/demo_2/2016-06/17/19-59-29.574/metadata/idr0016-wawer-bioactivecompoundprofiling/screens/24753.screen

 Error instantiating pixel buffer: /data/OMERO/ManagedRepository/demo_2/2016-06/17/19-59-29.574/metadata/idr0016-wawer-bioactivecompoundprofiling/screens/24753.screen

ERROR:omero.gateway:Failed to getPlane() or getTile() from rawPixelsStore

**Comment by manics** [comment]
It looks like a problem in our backend, a related error shows up if you try to open one of the images in plate `24753` https://idr.openmicroscopy.org/webclient/?show=plate-4995
We'll look into it.

**Comment by sunyi000** [comment]
Thanks Simon,

something I noticed when I tried open the url from the browser. not sure if this will help with debugging..

error: "KeyError('pixel_size',)"

Thanks for looking into it

**Comment by sbesson** [comment]
Hi @sunyi000, we reviewed this error while working on the latest IDR release. The server-side stack trace indicates that the source of the issue comes from a few TIFF files composing the screen which have been corrupted (size 0) following their publication in the resource.

The full list of affected files and associated plates under `idr0016` is:

| Plate name | Corrupted TIFF file                                                                                                                                                                     |
|--------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 25434  | /uod/idr/filesets/idr0016-wawer-bioactivecompoundprofiling/2016-02-19-screens-cellimagelibrary/25434-Mito/cdp2w10_f14_s4_w5def639e3-e8fc-4c9a-bf90-32e02e5aacd5.tif                |
| 26580  | /uod/idr/filesets/idr0016-wawer-bioactivecompoundprofiling/2016-02-19-screens-cellimagelibrary/26580-ERSytoBleed/cdp2w7x2_m13_s2_w3a2da12a8-9857-4027-a8ae-6c1e47bf80d2.tif        |
| 26115  | /uod/idr/filesets/idr0016-wawer-bioactivecompoundprofiling/2016-02-19-screens-cellimagelibrary/26115-Ph_golgi/cdp2w9x2_b13_s2_w49152fa4f-68a9-4158-85aa-7359830213ba.tif           |
| 24753  | /uod/idr/filesets/idr0016-wawer-bioactivecompoundprofiling/2016-02-19-screens-cellimagelibrary/24753-Mito/cdp2w5_f22_s6_w5cee4bb40-8b57-4c3f-9203-2caa9f09bf97.tif                 |
| 24295  | /uod/idr/filesets/idr0016-wawer-bioactivecompoundprofiling/2017-07-14-cellimagelibrary-60newplates/24295-Mito/cdp2bioactives_f08_s1_w5d1ea3aaf-70d0-4cf3-ada5-1e7a3ff53adf.tif     |
| 24310  | /uod/idr/filesets/idr0016-wawer-bioactivecompoundprofiling/2017-07-14-cellimagelibrary-60newplates/24310-Ph_golgi/cdp2bioactives_j20_s3_w4a5238acb-9175-40f4-a5ff-bd9dd5cf4484.tif |

It looks like we have a copy of the original files. We will perform a few checks and look into fixing these files in place on the IDR server. We will update this issue when the error is resolved.

- [x] Plate 25434
- [x] Plate 26580
- [x] Plate 26115
- [x] Plate 24753
- [x] Plate 24295
- [x] Plate 24310

**Comment by sbesson** [comment]
@sunyi000 all corrupted files have now been replaced and the cache files regenerated server-side. To the best of our knowledge, the failing plates for this screen should now be working again. Please try again and let us know if you experience problems. Thanks for spending the time to report.
