### ISSUE TITLE
Get images separated by planes

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#3]
I'm trying to get the original images from the OME server but I get a jpg file with all planes together. I'd like to know if there is any way to get the images separated by planes. If that's not possible, how can I get the OME-TIFF file instead of jpg?

Thanks in advance!

**Comment by joshmoore** [comment]
Hi @beatrizserrano 

> I'd like to know if there is any way to get the images separated by planes.

cF https://docs.openmicroscopy.org/latest/omero5.3/developers/Web/WebGateway.html#images (since IDR is still at OMERO 5.3)

I assume you're currently doing something like:

https://idr.openmicroscopy.org/webclient/render_image/179736/0/0/?c=1|167:2000$FF0000,2|288:4095$00FF00&m=c&p=normal&ia=0&q=0.9&maps=[{%22reverse%22:{%22enabled%22:false}},{%22reverse%22:{%22enabled%22:false}}]


![2 channels](https://idr.openmicroscopy.org/webclient/render_image/179736/0/0/?c=1|167:2000$FF0000,2|288:4095$00FF00&m=c&p=normal&ia=0&q=0.9&maps=[{%22reverse%22:{%22enabled%22:false}},{%22reverse%22:{%22enabled%22:false}}])



and what you're looking for is a single channel?

https://idr.openmicroscopy.org/webclient/render_image/179736/0/0/?c=1|167:2000$FF0000,-2|288:4095$00FF00&m=c&p=normal&ia=0&q=0.9&maps=[{%22reverse%22:{%22enabled%22:false}},{%22reverse%22:{%22enabled%22:false}}]

![1 channel](https://idr.openmicroscopy.org/webclient/render_image/179736/0/0/?c=1|167:2000$FF0000,-2|288:4095$00FF00&m=c&p=normal&ia=0&q=0.9&maps=[{%22reverse%22:{%22enabled%22:false}},{%22reverse%22:{%22enabled%22:false}}])


(The difference being the `-` before the 2 in `c=...,2`.)

> how can I get the OME-TIFF file instead of jpg?

An OME-TIFF doesn't necessarily exist for every imagine in the IDR. You can have a TIFF generated, but as the API currently stands, I don't think that's going to give you the best performance.

~Josh

**Comment by beatrizserrano** [comment]
Thanks a lot @joshmoore
