### ISSUE TITLE
No handlers could be found for logger "omero.gateway"

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#8]
I'm getting this warning each time I open a connection, but I can compute the features afterwards. Could this affect the results in some way?

**Comment by joshmoore** [comment]
Hi @beatrizserrano, it's strictly a logging issue so it should impact your results at all. See https://docs.python.org/2/library/logging.html#logging.basicConfig for options that you have in your local environment. So rather than:

```
>>> import omero
>>> import omero.gateway
No handlers could be found for logger "omero.gateway"
```

you could use:

```
>>> import logging
>>> logging.basicConfig()
>>> import omero
>>> import omero.gateway
```

adjusting the `level` argument to fit your needs.
